name: ci

on:
  push:
    paths-ignore:
    - 'doc/**'
    - 'changelog.md'
    - 'readme.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Build & test (Debug)
      run: dotnet test src --configuration Debug

    - name: Build & test (Release)
      run: dotnet test src --configuration Release

    - name: Pack
      run: dotnet pack src --configuration Release

    - name: Publish
      if: github.event_name == 'push'
      run: |      
          if [[ ${{ github.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              dotnet nuget push src/LibObjectFile/bin/Release/*.nupkg -s nuget.org -k ${{secrets.NUGET_TOKEN}}
          else
              echo publish is only enabled by tagging with a release tag
          fi

